//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace cfg.Datas
{
   
public partial class TbskillCfgData
{
    private readonly Dictionary<int, Datas.skillCfgData> _dataMap;
    private readonly List<Datas.skillCfgData> _dataList;
    
    public TbskillCfgData(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Datas.skillCfgData>();
        _dataList = new List<Datas.skillCfgData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Datas.skillCfgData _v;
            _v = Datas.skillCfgData.DeserializeskillCfgData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Datas.skillCfgData> DataMap => _dataMap;
    public List<Datas.skillCfgData> DataList => _dataList;

    public Datas.skillCfgData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Datas.skillCfgData Get(int key) => _dataMap[key];
    public Datas.skillCfgData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}