//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;



namespace cfg
{

public sealed partial class SkillCfg :  Bright.Config.BeanBase 
{
    public SkillCfg(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        name = _buf.ReadString();
        spellTime = _buf.ReadLong();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);buffList = new System.Collections.Generic.List<int>(n);for(var i = 0 ; i < n ; i++) { int _e;  _e = _buf.ReadInt(); buffList.Add(_e);}}
        PostInit();
    }

    public static SkillCfg DeserializeSkillCfg(ByteBuf _buf)
    {
        return new SkillCfg(_buf);
    }

    public int id { get; private set; }
    public string name { get; private set; }
    public long spellTime { get; private set; }
    public System.Collections.Generic.List<int> buffList { get; private set; }
    public System.Collections.Generic.List<BuffCfg> buffList_Ref { get; private set; }

    public const int __ID__ = -2087897997;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        { Datas.TbBuffCfg __table = (Datas.TbBuffCfg)_tables["Datas.TbBuffCfg"]; this.buffList_Ref = new System.Collections.Generic.List<BuffCfg>(); foreach(var __e in buffList) { this.buffList_Ref.Add(__table.GetOrDefault(__e)); } }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "spellTime:" + spellTime + ","
        + "buffList:" + Bright.Common.StringUtil.CollectionToString(buffList) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
