//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;


namespace cfg
{
   
public partial class Tables
{
    public Datas.TbskillCfgData TbskillCfgData {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbskillCfgData = new Datas.TbskillCfgData(loader("datas_tbskillcfgdata")); 
        tables.Add("Datas.TbskillCfgData", TbskillCfgData);

        PostInit();
        TbskillCfgData.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbskillCfgData.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}