//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Bright.Serialization;
using System.Collections.Generic;
using Sirenix.OdinInspector;


namespace cfg.Datas
{

[Serializable]
public sealed partial class skillCfgData :  Bright.Config.BeanBase 
{
    public skillCfgData(ByteBuf _buf) 
    {
        id = _buf.ReadInt();
        name = _buf.ReadString();
        spellTime = _buf.ReadLong();
        {int n = System.Math.Min(_buf.ReadSize(), _buf.Size);buffList = new System.Collections.Generic.List<int>(n);for(var i = 0 ; i < n ; i++) { int _e;  _e = _buf.ReadInt(); buffList.Add(_e);}}
        PostInit();
    }

    public static skillCfgData DeserializeskillCfgData(ByteBuf _buf)
    {
        return new Datas.skillCfgData(_buf);
    }

    [VerticalGroup("常规")]
    public int id { get; private set; }
    [VerticalGroup("常规")]
    public string name { get; private set; }
    public long spellTime { get; private set; }
    public System.Collections.Generic.List<int> buffList { get; private set; }

    public const int __ID__ = 704809602;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + id + ","
        + "name:" + name + ","
        + "spellTime:" + spellTime + ","
        + "buffList:" + Bright.Common.StringUtil.CollectionToString(buffList) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}
