//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;


namespace cfg
{
   
public partial class Tables
{
    public Datas.TbSkillCfg TbSkillCfg {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbSkillCfg = new Datas.TbSkillCfg(loader("datas_tbskillcfg")); 
        tables.Add("Datas.TbSkillCfg", TbSkillCfg);

        PostInit();
        TbSkillCfg.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbSkillCfg.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}